Define chassis_db_address at sonic level and remove it from per platform SKU definition. (#25733)
* Remove chassis_db_address address definition in platform SKU, move it ro a common place

* fix indentation

* Update config-chassisdb

* Use chassis_db_address irself instead of midplane_interface_ip

* missed to add this new j2 file which was created for this fix: chassisdb_address.j2

* Update a varible missed in PR

* Minor fixes

* Add smartswitch support to unify the chassis db adress

* Fix to make the checks robust, exit(1) so that systemd will tell service failed than telling it exited

* Fix LINECARD to LINE-CARD

* Reordered the logixc so that disagg, smartswitch, sup checked first and linecard last with additional try-catch

* Skip on virtual switch (docker-sonic-vs handles chassis-db internally)

* Update virtual switch logic to not call new platform APIs added as most of them is not supported

* Remove error print to reduce logging

* In disagg chassis use static docker.service.conf file to get docker0 bridge IP

* Add a retry (if at all needed) in case of sup and linecard to get midplane_ip

* Minor fix based on comment

* Increase the retry to 180sec as there is longer delay seen in ip address being set to interface in certain platforms on First boot. This is safe as this is config-chassisdb is a oneshot service and database-chassis service waits for it to finish before start

diff --git a/files/image_config/config-chassisdb/config-chassisdb b/files/image_config/config-chassisdb/config-chassisdb
--- a/files/image_config/config-chassisdb/config-chassisdb
+++ b/files/image_config/config-chassisdb/config-chassisdb
@@ -1,21 +1,5 @@
 #!/bin/bash
 ###########################################################################
-# Copyright 2020 Arista. The term "Arista" refers to Arista Inc.          #
-# and/or its subsidiaries.                                                #
-#                                                                         #
-# Licensed under the Apache License, Version 2.0 (the "License");         #
-# you may not use this file except in compliance with the License.        #
-# You may obtain a copy of the License at                                 #
-#                                                                         #
-#   http://www.apache.org/licenses/LICENSE-2.0                            #
-#                                                                         #
-# Unless required by applicable law or agreed to in writing, software     #
-# distributed under the License is distributed on an "AS IS" BASIS,       #
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.#
-# See the License for the specific language governing permissions and     #
-# limitations under the License.                                          #
-#                                                                         #
-###########################################################################
 # SONiC chassis_db configuration                                          #
 #                                                                         #
 # This script is used to add chassis_db address in local hosts and        #
@@ -26,7 +10,9 @@
 
 config_chassis_db() {
     startdb_file="/etc/sonic/chassisdb.conf"
+    chassisdb_address_file="/etc/sonic/chassisdb_address"
     [ ! -e $startdb_file ] || rm $startdb_file
+    [ ! -e $chassisdb_address_file ] || rm $chassisdb_address_file
     platform=${PLATFORM:-`sonic-cfggen -H -v DEVICE_METADATA.localhost.platform`}
     # database-chassis services will start when $chassis_config file exists
     chassis_config="/usr/share/sonic/device/$platform/chassisdb.conf"
@@ -34,23 +20,106 @@ config_chassis_db() {
        echo "no chassisdb.conf found, bypass config-chassisdb service"
        exit 0
     fi
+
+    # On virtual switch, retain the original flow, as it don't support most platform APIs
+    asic_type=$(python3 -c 'from sonic_py_common.device_info import get_sonic_version_info; \
+	                    print(get_sonic_version_info().get("asic_type") or "")')
+
+    if [[ "$asic_type" != "vs" ]]; then
+    # Read the various device attributes
+    read -r is_supervisor is_disagg is_smartswitch is_dpu < <(python3 -c \
+	    'import sonic_py_common.device_info as d; print(*[getattr(d,n,lambda:False)() \
+	    for n in ("is_supervisor","is_disaggregated_chassis","is_smartswitch","is_dpu")])')
+
+    # Identify the midplane IP in each sonic platform
+    if [[ "$is_disagg" == True ]]; then
+        # With disagg T2 pizza box docker0 bridge is the midplane, Extract it from dockerd.conf
+        docker_conf="/etc/systemd/system/docker.service.d/docker.service.conf"
+        [[ $(<"$docker_conf") =~ --bip=([0-9.]+) ]] && midplane_interface_ip="${BASH_REMATCH[1]}"
+    elif [[ "$is_smartswitch" == True ]] || [[ "$is_dpu" == True ]]; then
+        # On smartswitch (NPU or DPU side) get the NPU bridge-midplane IP from the network config file
+        midplane_interface_ip=$(python3 -c \
+            'import sonic_py_common.device_info as d; print(d.get_smartswitch_midplane_ip() or "")')
+    elif [[ "$is_supervisor" == True ]]; then
+        # supervisor: midplane IP is on eth1-midplane. Add retry for 180sec
+        midplane_interface_ip=""
+        for i in {1..36}; do
+            midplane_interface_ip=$(ip -4 -o addr show "eth1-midplane" 2>/dev/null | \
+                                  awk '{print $4}' | cut -d/ -f1 | head -n1)
+            [[ -n "$midplane_interface_ip" ]] && break
+            echo "eth1-midplane IP not available yet (attempt $i/36); retrying in 5s..."
+            sleep 5
+        done
+    else
+        # linecard: query supervisor's midplane IP via platform API. Add retry for 180sec
+        midplane_interface_ip=""
+        for i in {1..36}; do
+            midplane_interface_ip=$(python3 -c "
+try:
+    import sonic_platform.platform as p
+    c = p.Platform().get_chassis()
+    s = c.get_supervisor_slot()
+    m = [x.get_midplane_ip() for x in c.get_all_modules()
+         if x.get_slot() == s]
+    print(m[0] if m else '')
+except Exception:
+    print('')")
+            [[ -n "$midplane_interface_ip" ]] && break
+            echo "Supervisor midplane IP not available via platform API yet (attempt $i/36); retrying in 5s..."
+            sleep 5
+        done
+    fi
+
+    # Generate the chassisdb_address_file from the midplane interface ip address
+    if [[ -n "$midplane_interface_ip" ]]; then
+        echo "chassis_db_address=$midplane_interface_ip" > "$chassisdb_address_file"
+    else
+        echo "Error: No IP address configured on midplane_interface"
+        exit 1
+    fi
+    fi
+
     start_chassis_db=0
     chassis_db_address=""
+
+    # source the platform/sku level chassisdb.conf, if the file exists
     source $chassis_config
+    # source the new chassisdb_address_file, if the file exists
+    [ -f $chassisdb_address_file ] && source $chassisdb_address_file
+
+    # Introduce additional checks so that the chassis_db_address is valid
+    # Check if the IP address is not 0.0.0.0
+    if [[ "$chassis_db_address" == "0.0.0.0" ]]; then
+        echo "Error: chassis_db address configured as 0.0.0.0"
+        [ ! -e $chassisdb_address_file ] || rm $chassisdb_address_file
+        exit 1
+    fi
+    # if the midplane subnet is defined make sure the IP address is part of the midplane subnet
+    if [[ -n "$midplane_subnet" ]]; then
+        result=$(python3 -c "import ipaddress; print(ipaddress.ip_address('$chassis_db_address') \
+              in ipaddress.ip_network('$midplane_subnet'))")
+        # Exit as error if chassis_db_address not in the midplane subnet or if validation fails
+        if [[ $? -ne 0 ]] || [[ "$result" == "False" ]]; then
+            echo "Error: chassis_db address does not belong to midplane subnet"
+            [ ! -e $chassisdb_address_file ] || rm $chassisdb_address_file
+            exit 1
+        fi
+    fi
+
     if [[ "$start_chassis_db" == "1" ]]; then
        cp $chassis_config $startdb_file
        echo "start chassisdb"
     fi
     if [[ "$start_chassis_db" == "1" ]] || [[ -n "$chassis_db_address" ]]; then
-       if [ -z "$chassis_db_address" ]; then
-	  echo "no user configured chassisdb address"
-       else
-          grep redis_chassis /etc/hosts
-          if [ $? -ne 0 ]; then
-            echo "$chassis_db_address redis_chassis.server" >> /etc/hosts
-            echo "update chassis db address to $chassis_db_address"
-          fi
-       fi
+        if [ -z "$chassis_db_address" ]; then
+            echo "no user configured chassisdb address"
+        else
+            grep redis_chassis /etc/hosts
+            if [ $? -ne 0 ]; then
+                echo "$chassis_db_address redis_chassis.server" >> /etc/hosts
+                echo "update chassis db address to $chassis_db_address"
+            fi
+        fi
     fi
 }
 
